import { SlEnergy } from "react-icons/sl";
import useTrade from "../../../../hooks/useTrade";

const TradeEng = () => {
  const [treads] = useTrade();

  // ✅ Total Sold Energy (amount of money earned)
  const totalSoldEnergy =
    treads
      ?.filter((trade) => trade.status === "sold")
      ?.reduce((acc, trade) => acc + trade.price, 0) || 0;

  // ✅ Total Produced Energy (all trades)
  const totalProducedEnergy =
    treads?.reduce((acc, trade) => acc + trade.sellEnergyAmount, 0) || 0;

  return (
    <div className="flex flex-wrap gap-6">
      {/* Total Produced Energy */}
      <div
        className="
          bg-white
          border border-gray-200
          rounded-2xl
          shadow-sm
          hover:shadow-md
          transition-all
          duration-200
          p-6
          flex flex-col
          justify-between
          w-80
        "
      >
        <h2 className="text-lg font-semibold text-gray-700 mb-3">
          Total Energy Produced
        </h2>
        <div className="flex items-center gap-3">
          <div className="flex items-center justify-center w-12 h-12 rounded-full bg-green-100 text-green-600">
            <SlEnergy size={26} />
          </div>
          <p className="text-3xl font-bold text-gray-800">
            {totalProducedEnergy}
          </p>
        </div>
        <p className="mt-3 text-sm text-gray-500">
          Total energy generated by all users
        </p>
      </div>

      {/* Total Energy Traded */}
      <div
        className="
          bg-white
          border border-gray-200
          rounded-2xl
          shadow-sm
          hover:shadow-md
          transition-all
          duration-200
          p-6
          flex flex-col
          justify-between
          w-80
        "
      >
        <h2 className="text-lg font-semibold text-gray-700 mb-3">
          Total Energy Traded
        </h2>
        <div className="flex items-center gap-3">
          <div className="flex items-center justify-center w-12 h-12 rounded-full bg-sky-100 text-sky-600">
            <SlEnergy size={26} />
          </div>
          <p className="text-3xl font-bold text-gray-800">
            {totalSoldEnergy} ৳
          </p>
        </div>
        <p className="mt-3 text-sm text-gray-500">
          Total amount earned from sold energy
        </p>
      </div>
    </div>
  );
};

export default TradeEng;
